/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class DistanceJoint extends Joint {
  private transient long swigCPtr;

  protected DistanceJoint(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.DistanceJoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DistanceJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.DistanceJoint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public void setLength(float length) {
    liquidfunJNI.DistanceJoint_setLength(swigCPtr, this, length);
  }

  public float getLength() {
    return liquidfunJNI.DistanceJoint_getLength(swigCPtr, this);
  }

  public void setFrequency(float hz) {
    liquidfunJNI.DistanceJoint_setFrequency(swigCPtr, this, hz);
  }

  public float getFrequency() {
    return liquidfunJNI.DistanceJoint_getFrequency(swigCPtr, this);
  }

  public void setDampingRatio(float ratio) {
    liquidfunJNI.DistanceJoint_setDampingRatio(swigCPtr, this, ratio);
  }

  public float getDampingRatio() {
    return liquidfunJNI.DistanceJoint_getDampingRatio(swigCPtr, this);
  }

  public void dump() {
    liquidfunJNI.DistanceJoint_dump(swigCPtr, this);
  }

}
