/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class JointDef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected JointDef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_JointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(JointType value) {
    liquidfunJNI.JointDef_type_set(swigCPtr, this, value.swigValue());
  }

  public JointType getType() {
    return JointType.swigToEnum(liquidfunJNI.JointDef_type_get(swigCPtr, this));
  }

  public void setBodyA(Body value) {
    liquidfunJNI.JointDef_bodyA_set(swigCPtr, this, Body.getCPtr(value), value);
  }

  public Body getBodyA() {
    long cPtr = liquidfunJNI.JointDef_bodyA_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public void setBodyB(Body value) {
    liquidfunJNI.JointDef_bodyB_set(swigCPtr, this, Body.getCPtr(value), value);
  }

  public Body getBodyB() {
    long cPtr = liquidfunJNI.JointDef_bodyB_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Body(cPtr, false);
  }

  public void setCollideConnected(boolean value) {
    liquidfunJNI.JointDef_collideConnected_set(swigCPtr, this, value);
  }

  public boolean getCollideConnected() {
    return liquidfunJNI.JointDef_collideConnected_get(swigCPtr, this);
  }

  public JointDef() {
    this(liquidfunJNI.new_JointDef(), true);
  }

}
