/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class PrismaticJointDef extends JointDef {
  private transient long swigCPtr;

  protected PrismaticJointDef(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.PrismaticJointDef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrismaticJointDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_PrismaticJointDef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setLocalAnchorA(float x, float y) {
    liquidfunJNI.PrismaticJointDef_setLocalAnchorA(swigCPtr, this, x, y);
  }

  public void setLocalAnchorB(float x, float y) {
    liquidfunJNI.PrismaticJointDef_setLocalAnchorB(swigCPtr, this, x, y);
  }

  public void setLocalAxisA(float x, float y) {
    liquidfunJNI.PrismaticJointDef_setLocalAxisA(swigCPtr, this, x, y);
  }

  public void setReferenceAngle(float value) {
    liquidfunJNI.PrismaticJointDef_referenceAngle_set(swigCPtr, this, value);
  }

  public float getReferenceAngle() {
    return liquidfunJNI.PrismaticJointDef_referenceAngle_get(swigCPtr, this);
  }

  public void setEnableLimit(boolean value) {
    liquidfunJNI.PrismaticJointDef_enableLimit_set(swigCPtr, this, value);
  }

  public boolean getEnableLimit() {
    return liquidfunJNI.PrismaticJointDef_enableLimit_get(swigCPtr, this);
  }

  public void setLowerTranslation(float value) {
    liquidfunJNI.PrismaticJointDef_lowerTranslation_set(swigCPtr, this, value);
  }

  public float getLowerTranslation() {
    return liquidfunJNI.PrismaticJointDef_lowerTranslation_get(swigCPtr, this);
  }

  public void setUpperTranslation(float value) {
    liquidfunJNI.PrismaticJointDef_upperTranslation_set(swigCPtr, this, value);
  }

  public float getUpperTranslation() {
    return liquidfunJNI.PrismaticJointDef_upperTranslation_get(swigCPtr, this);
  }

  public void setEnableMotor(boolean value) {
    liquidfunJNI.PrismaticJointDef_enableMotor_set(swigCPtr, this, value);
  }

  public boolean getEnableMotor() {
    return liquidfunJNI.PrismaticJointDef_enableMotor_get(swigCPtr, this);
  }

  public void setMaxMotorForce(float value) {
    liquidfunJNI.PrismaticJointDef_maxMotorForce_set(swigCPtr, this, value);
  }

  public float getMaxMotorForce() {
    return liquidfunJNI.PrismaticJointDef_maxMotorForce_get(swigCPtr, this);
  }

  public void setMotorSpeed(float value) {
    liquidfunJNI.PrismaticJointDef_motorSpeed_set(swigCPtr, this, value);
  }

  public float getMotorSpeed() {
    return liquidfunJNI.PrismaticJointDef_motorSpeed_get(swigCPtr, this);
  }

  public PrismaticJointDef() {
    this(liquidfunJNI.new_PrismaticJointDef(), true);
  }

}
