/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class RevoluteJoint extends Joint {
  private transient long swigCPtr;

  protected RevoluteJoint(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.RevoluteJoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RevoluteJoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public float getReferenceAngle() {
    return liquidfunJNI.RevoluteJoint_getReferenceAngle(swigCPtr, this);
  }

  public float getJointAngle() {
    return liquidfunJNI.RevoluteJoint_getJointAngle(swigCPtr, this);
  }

  public float getJointSpeed() {
    return liquidfunJNI.RevoluteJoint_getJointSpeed(swigCPtr, this);
  }

  public boolean isLimitEnabled() {
    return liquidfunJNI.RevoluteJoint_isLimitEnabled(swigCPtr, this);
  }

  public void enableLimit(boolean flag) {
    liquidfunJNI.RevoluteJoint_enableLimit(swigCPtr, this, flag);
  }

  public float getLowerLimit() {
    return liquidfunJNI.RevoluteJoint_getLowerLimit(swigCPtr, this);
  }

  public float getUpperLimit() {
    return liquidfunJNI.RevoluteJoint_getUpperLimit(swigCPtr, this);
  }

  public void setLimits(float lower, float upper) {
    liquidfunJNI.RevoluteJoint_setLimits(swigCPtr, this, lower, upper);
  }

  public boolean isMotorEnabled() {
    return liquidfunJNI.RevoluteJoint_isMotorEnabled(swigCPtr, this);
  }

  public void enableMotor(boolean flag) {
    liquidfunJNI.RevoluteJoint_enableMotor(swigCPtr, this, flag);
  }

  public void setMotorSpeed(float speed) {
    liquidfunJNI.RevoluteJoint_setMotorSpeed(swigCPtr, this, speed);
  }

  public float getMotorSpeed() {
    return liquidfunJNI.RevoluteJoint_getMotorSpeed(swigCPtr, this);
  }

  public void setMaxMotorTorque(float torque) {
    liquidfunJNI.RevoluteJoint_setMaxMotorTorque(swigCPtr, this, torque);
  }

  public float getMaxMotorTorque() {
    return liquidfunJNI.RevoluteJoint_getMaxMotorTorque(swigCPtr, this);
  }

  public float getReactionTorque(float inv_dt) {
    return liquidfunJNI.RevoluteJoint_getReactionTorque(swigCPtr, this, inv_dt);
  }

  public float getMotorTorque(float inv_dt) {
    return liquidfunJNI.RevoluteJoint_getMotorTorque(swigCPtr, this, inv_dt);
  }

  public void dump() {
    liquidfunJNI.RevoluteJoint_dump(swigCPtr, this);
  }

}
